name: Generate Weekly Summary

on:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at 12:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas

    - name: Run summary script
      run: python generate_summary.py

    - name: Commit summary
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add summaries/
        git commit -m "📊 Weekly summary update"
        git push
